package com.benoitlefevre.monbudget.utils

import com.benoitlefevre.monbudget.database.models.ExpenseType
import com.google.common.truth.Truth.assertThat
import org.junit.Before

import org.junit.Test

class ExpenseTypeConverterTest {

    private lateinit var converter: ExpenseTypeConverter

    @Before
    fun setUp() {
        converter = ExpenseTypeConverter()
    }

    @Test
    fun toExpenseType_success_correctExpenseTypeReturned() {
        var expenseType = converter.toExpenseType(0)
        assertThat(expenseType).isEqualTo(ExpenseType.FOOD)
        expenseType = converter.toExpenseType(1)
        assertThat(expenseType).isEqualTo(ExpenseType.RESTAURANT)
        expenseType = converter.toExpenseType(2)
        assertThat(expenseType).isEqualTo(ExpenseType.CAFETERIA)
        expenseType = converter.toExpenseType(3)
        assertThat(expenseType).isEqualTo(ExpenseType.VEHICLE)
        expenseType = converter.toExpenseType(4)
        assertThat(expenseType).isEqualTo(ExpenseType.PUBLIC_TRANSPORT)
        expenseType = converter.toExpenseType(5)
        assertThat(expenseType).isEqualTo(ExpenseType.TOLLS)
        expenseType = converter.toExpenseType(6)
        assertThat(expenseType).isEqualTo(ExpenseType.GASOLINE)
        expenseType = converter.toExpenseType(7)
        assertThat(expenseType).isEqualTo(ExpenseType.CAR_INSURANCE)
        expenseType = converter.toExpenseType(8)
        assertThat(expenseType).isEqualTo(ExpenseType.CAR_PARK)
        expenseType = converter.toExpenseType(9)
        assertThat(expenseType).isEqualTo(ExpenseType.HEALTH)
        expenseType = converter.toExpenseType(10)
        assertThat(expenseType).isEqualTo(ExpenseType.DOCTOR)
        expenseType = converter.toExpenseType(11)
        assertThat(expenseType).isEqualTo(ExpenseType.PHARMACY)
        expenseType = converter.toExpenseType(12)
        assertThat(expenseType).isEqualTo(ExpenseType.MUTUAL_HEALTH)
        expenseType = converter.toExpenseType(13)
        assertThat(expenseType).isEqualTo(ExpenseType.HEALTH_INSURANCE)
        expenseType = converter.toExpenseType(14)
        assertThat(expenseType).isEqualTo(ExpenseType.BANK_FEES)
        expenseType = converter.toExpenseType(15)
        assertThat(expenseType).isEqualTo(ExpenseType.BANK_LOAN)
        expenseType = converter.toExpenseType(16)
        assertThat(expenseType).isEqualTo(ExpenseType.ACCOUNT_FEES)
        expenseType = converter.toExpenseType(17)
        assertThat(expenseType).isEqualTo(ExpenseType.THRIFT)
        expenseType = converter.toExpenseType(18)
        assertThat(expenseType).isEqualTo(ExpenseType.WITHDRAWAL)
        expenseType = converter.toExpenseType(19)
        assertThat(expenseType).isEqualTo(ExpenseType.STOCK_EXCHANGE)
        expenseType = converter.toExpenseType(20)
        assertThat(expenseType).isEqualTo(ExpenseType.HOUSING)
        expenseType = converter.toExpenseType(21)
        assertThat(expenseType).isEqualTo(ExpenseType.HOUSING_INSURANCE)
        expenseType = converter.toExpenseType(22)
        assertThat(expenseType).isEqualTo(ExpenseType.HOUSING_TAX)
        expenseType = converter.toExpenseType(23)
        assertThat(expenseType).isEqualTo(ExpenseType.PROPERTY_TAX)
        expenseType = converter.toExpenseType(24)
        assertThat(expenseType).isEqualTo(ExpenseType.REAL_ESTATE_LOAN)
        expenseType = converter.toExpenseType(25)
        assertThat(expenseType).isEqualTo(ExpenseType.ELECTRICITY_GAZ_WATER)
        expenseType = converter.toExpenseType(26)
        assertThat(expenseType).isEqualTo(ExpenseType.RENTAL)
        expenseType = converter.toExpenseType(27)
        assertThat(expenseType).isEqualTo(ExpenseType.FURNISHINGS)
        expenseType = converter.toExpenseType(28)
        assertThat(expenseType).isEqualTo(ExpenseType.GARDENING)
        expenseType = converter.toExpenseType(29)
        assertThat(expenseType).isEqualTo(ExpenseType.TAXES)
        expenseType = converter.toExpenseType(30)
        assertThat(expenseType).isEqualTo(ExpenseType.INCOME_TAX)
        expenseType = converter.toExpenseType(31)
        assertThat(expenseType).isEqualTo(ExpenseType.LIFE_INSURANCE)
        expenseType = converter.toExpenseType(32)
        assertThat(expenseType).isEqualTo(ExpenseType.AGIOS)
        expenseType = converter.toExpenseType(33)
        assertThat(expenseType).isEqualTo(ExpenseType.PROFESSIONAL_FEES)
        expenseType = converter.toExpenseType(34)
        assertThat(expenseType).isEqualTo(ExpenseType.TUITION_FEES)
        expenseType = converter.toExpenseType(35)
        assertThat(expenseType).isEqualTo(ExpenseType.OTHER_EXPENSE)
        expenseType = converter.toExpenseType(36)
        assertThat(expenseType).isEqualTo(ExpenseType.GIFT)
        expenseType = converter.toExpenseType(37)
        assertThat(expenseType).isEqualTo(ExpenseType.PHONE)
        expenseType = converter.toExpenseType(38)
        assertThat(expenseType).isEqualTo(ExpenseType.INTERNET)
        expenseType = converter.toExpenseType(39)
        assertThat(expenseType).isEqualTo(ExpenseType.ANIMALS)
        expenseType = converter.toExpenseType(40)
        assertThat(expenseType).isEqualTo(ExpenseType.MULTIMEDIA)
        expenseType = converter.toExpenseType(41)
        assertThat(expenseType).isEqualTo(ExpenseType.SPORT)
        expenseType = converter.toExpenseType(42)
        assertThat(expenseType).isEqualTo(ExpenseType.HOLIDAYS)
        expenseType = converter.toExpenseType(43)
        assertThat(expenseType).isEqualTo(ExpenseType.BOOKS)
        expenseType = converter.toExpenseType(44)
        assertThat(expenseType).isEqualTo(ExpenseType.GAMES)
        expenseType = converter.toExpenseType(45)
        assertThat(expenseType).isEqualTo(ExpenseType.HOBBIES)
        expenseType = converter.toExpenseType(46)
        assertThat(expenseType).isEqualTo(ExpenseType.HAIRDRESSER)
        expenseType = converter.toExpenseType(47)
        assertThat(expenseType).isEqualTo(ExpenseType.CLOTHING)
        expenseType = converter.toExpenseType(48)
        assertThat(expenseType).isEqualTo(ExpenseType.SHOES)
        expenseType = converter.toExpenseType(49)
        assertThat(expenseType).isEqualTo(ExpenseType.FASHION_ACCESSORY)
        expenseType = converter.toExpenseType(50)
        assertThat(expenseType).isEqualTo(ExpenseType.NONE)
    }

    @Test
    fun fromExpenseType_success_correctIntReturned() {
        var ordinal = converter.fromExpenseType(ExpenseType.NONE)
        assertThat(ordinal).isEqualTo(50)
        ordinal = converter.fromExpenseType(ExpenseType.FASHION_ACCESSORY)
        assertThat(ordinal).isEqualTo(49)
        ordinal = converter.fromExpenseType(ExpenseType.SHOES)
        assertThat(ordinal).isEqualTo(48)
        ordinal = converter.fromExpenseType(ExpenseType.CLOTHING)
        assertThat(ordinal).isEqualTo(47)
        ordinal = converter.fromExpenseType(ExpenseType.HAIRDRESSER)
        assertThat(ordinal).isEqualTo(46)
        ordinal = converter.fromExpenseType(ExpenseType.HOBBIES)
        assertThat(ordinal).isEqualTo(45)
        ordinal = converter.fromExpenseType(ExpenseType.GAMES)
        assertThat(ordinal).isEqualTo(44)
        ordinal = converter.fromExpenseType(ExpenseType.BOOKS)
        assertThat(ordinal).isEqualTo(43)
        ordinal = converter.fromExpenseType(ExpenseType.HOLIDAYS)
        assertThat(ordinal).isEqualTo(42)
        ordinal = converter.fromExpenseType(ExpenseType.SPORT)
        assertThat(ordinal).isEqualTo(41)
        ordinal = converter.fromExpenseType(ExpenseType.MULTIMEDIA)
        assertThat(ordinal).isEqualTo(40)
        ordinal = converter.fromExpenseType(ExpenseType.ANIMALS)
        assertThat(ordinal).isEqualTo(39)
        ordinal = converter.fromExpenseType(ExpenseType.INTERNET)
        assertThat(ordinal).isEqualTo(38)
        ordinal = converter.fromExpenseType(ExpenseType.PHONE)
        assertThat(ordinal).isEqualTo(37)
        ordinal = converter.fromExpenseType(ExpenseType.GIFT)
        assertThat(ordinal).isEqualTo(36)
        ordinal = converter.fromExpenseType(ExpenseType.OTHER_EXPENSE)
        assertThat(ordinal).isEqualTo(35)
        ordinal = converter.fromExpenseType(ExpenseType.TUITION_FEES)
        assertThat(ordinal).isEqualTo(34)
        ordinal = converter.fromExpenseType(ExpenseType.PROFESSIONAL_FEES)
        assertThat(ordinal).isEqualTo(33)
        ordinal = converter.fromExpenseType(ExpenseType.AGIOS)
        assertThat(ordinal).isEqualTo(32)
        ordinal = converter.fromExpenseType(ExpenseType.LIFE_INSURANCE)
        assertThat(ordinal).isEqualTo(31)
        ordinal = converter.fromExpenseType(ExpenseType.INCOME_TAX)
        assertThat(ordinal).isEqualTo(30)
        ordinal = converter.fromExpenseType(ExpenseType.TAXES)
        assertThat(ordinal).isEqualTo(29)
        ordinal = converter.fromExpenseType(ExpenseType.GARDENING)
        assertThat(ordinal).isEqualTo(28)
        ordinal = converter.fromExpenseType(ExpenseType.FURNISHINGS)
        assertThat(ordinal).isEqualTo(27)
        ordinal = converter.fromExpenseType(ExpenseType.RENTAL)
        assertThat(ordinal).isEqualTo(26)
        ordinal = converter.fromExpenseType(ExpenseType.ELECTRICITY_GAZ_WATER)
        assertThat(ordinal).isEqualTo(25)
        ordinal = converter.fromExpenseType(ExpenseType.REAL_ESTATE_LOAN)
        assertThat(ordinal).isEqualTo(24)
        ordinal = converter.fromExpenseType(ExpenseType.PROPERTY_TAX)
        assertThat(ordinal).isEqualTo(23)
        ordinal = converter.fromExpenseType(ExpenseType.HOUSING_TAX)
        assertThat(ordinal).isEqualTo(22)
        ordinal = converter.fromExpenseType(ExpenseType.HOUSING_INSURANCE)
        assertThat(ordinal).isEqualTo(21)
        ordinal = converter.fromExpenseType(ExpenseType.HOUSING)
        assertThat(ordinal).isEqualTo(20)
        ordinal = converter.fromExpenseType(ExpenseType.STOCK_EXCHANGE)
        assertThat(ordinal).isEqualTo(19)
        ordinal = converter.fromExpenseType(ExpenseType.WITHDRAWAL)
        assertThat(ordinal).isEqualTo(18)
        ordinal = converter.fromExpenseType(ExpenseType.THRIFT)
        assertThat(ordinal).isEqualTo(17)
        ordinal = converter.fromExpenseType(ExpenseType.ACCOUNT_FEES)
        assertThat(ordinal).isEqualTo(16)
        ordinal = converter.fromExpenseType(ExpenseType.BANK_LOAN)
        assertThat(ordinal).isEqualTo(15)
        ordinal = converter.fromExpenseType(ExpenseType.BANK_FEES)
        assertThat(ordinal).isEqualTo(14)
        ordinal = converter.fromExpenseType(ExpenseType.HEALTH_INSURANCE)
        assertThat(ordinal).isEqualTo(13)
        ordinal = converter.fromExpenseType(ExpenseType.MUTUAL_HEALTH)
        assertThat(ordinal).isEqualTo(12)
        ordinal = converter.fromExpenseType(ExpenseType.PHARMACY)
        assertThat(ordinal).isEqualTo(11)
        ordinal = converter.fromExpenseType(ExpenseType.DOCTOR)
        assertThat(ordinal).isEqualTo(10)
        ordinal = converter.fromExpenseType(ExpenseType.HEALTH)
        assertThat(ordinal).isEqualTo(9)
        ordinal = converter.fromExpenseType(ExpenseType.CAR_PARK)
        assertThat(ordinal).isEqualTo(8)
        ordinal = converter.fromExpenseType(ExpenseType.CAR_INSURANCE)
        assertThat(ordinal).isEqualTo(7)
        ordinal = converter.fromExpenseType(ExpenseType.GASOLINE)
        assertThat(ordinal).isEqualTo(6)
        ordinal = converter.fromExpenseType(ExpenseType.TOLLS)
        assertThat(ordinal).isEqualTo(5)
        ordinal = converter.fromExpenseType(ExpenseType.PUBLIC_TRANSPORT)
        assertThat(ordinal).isEqualTo(4)
        ordinal = converter.fromExpenseType(ExpenseType.VEHICLE)
        assertThat(ordinal).isEqualTo(3)
        ordinal = converter.fromExpenseType(ExpenseType.CAFETERIA)
        assertThat(ordinal).isEqualTo(2)
        ordinal = converter.fromExpenseType(ExpenseType.RESTAURANT)
        assertThat(ordinal).isEqualTo(1)
        ordinal = converter.fromExpenseType(ExpenseType.FOOD)
        assertThat(ordinal).isEqualTo(0)
    }
}